application:
  name: deps-rs
  project: deps-rs
  cloud_region: aws/us-west-2
  publicly_accessible: true
  storage:
    - name: images
      type: ssd
      size: 1GB
      mount_point: /data
routers:
- name: main
  custom_domains:
  - branch: setup-cd-with-qovery
    domain: deps.rm.rs
  - branch: main
    domain: deps.rs
  routes:
  - application_name: deps-rs
    paths:
    - /
