application:
  name: deps.rs
  project: deps.rs
  cloud_region: aws/us-west-2
  publicly_accessible: true
routers:
- name: main
  custom_domains:
  - branch: setup-cd-with-qovery
    domain: deps.rm.rs
  routes:
  - application_name: deps.rs
    paths:
    - /
