---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deps-rs
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  rules:
    - host: staging.deps.rs
      http:
        paths:
          - backend:
              service:
                name: deps-rs
                port:
                  name: http
            path: /
            pathType: Prefix
  tls:
    - secretName: deps-rs-tls
      hosts:
        - $(DOMAIN)
