apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

vars:
  - name: DOMAIN
    objref:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: deps-rs
    fieldref:
      fieldpath: spec.rules[0].host
