apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prd

commonLabels:
  env: prd

resources:
  - ../../base

patches:
  - path: patch-ingress.json
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: deps-rs
